# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: Kintaro AI
email: baraban@kintaroai.com
author: "Baraban" # Replace with your name
description: >-
  Your site's description here. This will appear in your document head meta
  (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g., /blog
url: "KintaroAI.com" # replace with your actual domain

# Social links
repo: "https://github.com/KintaroAI/com" # Replace with your repo URL
github_user: "KintaroAI"
github_repo: "com" # Replace with your repository name
github_branch: "master" # Or the default branch of your repo

# Optional social links
twitter: Kintaro_AI
linkedin: your-linkedin-username # Replace if you have one
dockerhub: your-dockerhub-username # Replace if applicable

# Theme settings
remote_theme: "vsoch/docsy-jekyll"
markdown: kramdown

# Appearance settings
tag_color: primary # Options: danger, success, warning, primary, info, secondary
accentColor: red # Options: red, purple, green, etc.
themeColor: red # Options: red, purple, green, blue, orange, purple, grey
fixedNav: true # true or false

# Logo and branding
# Uncomment and set these if you have a logo
logo: "assets/img/logo/your-logo.png"
logo_pixels: 34
color: "#30638e" # primary color for header, buttons

# Versioning (optional)
# version_params:
#   version_menu: "Release"
#   version_dir: Archive
#   tocversion_dir: versions
#   versioning: true
#   allow_search: true
#   search_versions:
#     - Previous
#   latest: Current
#   versions:
#     - Current
#     - Previous

# Feedback
feedback: false # Set to false if you don't want feedback buttons

# Privacy Policy
# privacy: https://www.kintaroai.com/privacy # Uncomment and set if you have one

# Google Analytics (optional)
# google-analytics: UA-XXXXXXXXXX

# Permalink structure
permalink: /:year/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site
  - CHANGELOG.md
  - LICENSE
  - README.md
  - vendor
  - deploy.sh
  - docker-compose.yaml
  - jekyll_build.sh
  - jekyll_dev_run.sh
  - jekyll_init.sh
  - nginx.sh

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      citation: true

